import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "./assets/scss/main.scss";
const pinia = createPinia();
let app = createApp(App);
app.use(router);
app.use(pinia);
app.mount("#app");
